### ISSUE TITLE
Can't build on Debian 11 Stable

### ISSUE THREAD

**Issue by vanfanel** [deathkiller/jazz2-native#1]
Hi! Just discovered that Jazz2 Resurrection has been ported to C++, it's a very nice thing and I hope to get this running on The Pi4 without X11 (it seems to target SDL2, so it will be possible to run the game without X11!!!)

However, trying to build on x86_64 Debian 11 Stable, I get some errors like this one:
```

/usr/include/c++/10/bits/basic_string.tcc:1481:50: error: expected primary-expression before ‘,’ token
 1481 |       typename __istream_type::sentry __cerb(__in, false);
```

Maybe it's not yet possible to build this C++ port? Maybe it hasn't been tested on Debian 11 where GCC is `gcc version 10.2.1`?

Thanks!

**Comment by deathkiller** [comment]
Hi! I'm working hard to port it, but it's not done yet. I test it mainly on Windows and web (Emscripten; http://deat.tk/jazz2/wasm/). And if it works on the web then I think it should work everywhere, but it's not tested anywhere else yet. Another issue is asset loader/converter is not done yet, so you need game data that you can't get anywhere yet, but I'm working on it.

Also I'm using C++20 standard, but it should work with up-to-date compiler. Your error message looks strange, because it references some file used by compiler, not source file of the game. I have Fedora 36, so I will try to build it there.

**Comment by deathkiller** [comment]
It should build on Linux with `./BuildLinuxClang.sh` (to `../Jazz2-LinuxClang-Release/` directory) now. You need to download and extract dependencies (https://github.com/nCine/nCine-libraries-artifacts/tree/libraries-linux-clang) to `../nCine-external/`. GCC throws some errors, I don't know how to suppress it yet. If you need some testing (demo) data until the loader/converter is ready, you can contact me on [Discord](https://discord.gg/Y7SBvkD).

**Comment by vanfanel** [comment]
@deathkiller Thanks for your work on this C++ port, really! :)
I got it to build with CLAG, yes, but will gcc be build-able? That's what the Raspberry Pi uses by default, for example... and I want to see this running on the lovely "computer of the masses" :P

**Comment by deathkiller** [comment]
GCC and SDL2 is build-able now! Game data loader is also completed (episodes are still not implemented, so you can play only Shareware Demo). You can copy `Content` directory to `<game-path>/Content/` (and probably also shaders from `Jazz2/nCine/Shaders/` to `<game-path>/Content/Shaders/`) and copy original JJ2 to `<game-path>/Source/`, then run the game. `<game-path>/Cache/` will be created on the first run.

**Comment by vanfanel** [comment]
> GCC and SDL2 is build-able now! Game data loader is also completed (episodes are still not implemented, so you can play only Shareware Demo). You can copy `Content` directory to `<game-path>/Content/` (and probably also shaders from `Jazz2/nCine/Shaders/` to `<game-path>/Content/Shaders/`) and copy original JJ2 to `<game-path>/Source/`, then run the game. `<game-path>/Cache/` will be created on the first run.

Wow, that was fast! I will test as soon as possible! :D

**Comment by coreybruce** [comment]
Hey there wanted to join in and test it out even tho it is no ready

So I tried to compile it with GCC and clang and they both failed but I do have the Clang log here for you since you mentioned that it should be compiled in Clang

Log:
https://gist.github.com/coreybruce/ffbb5b7b6e1038b8711b03dc9abb6f77

**Comment by deathkiller** [comment]
It should be fixed now, could you try it again? It should work with both GCC and Clang.

**Comment by coreybruce** [comment]
Awesome it compiled but my next issue is it core dumps after the cutscene, I tried it in the jazz2 folder and the original GOG Jazz 2 folder

**Comment by deathkiller** [comment]
So intro cutscene works, that's great! You can try to edit `BuildLinuxGcc.sh`/`BuildLinuxClang.sh` scripts and enable `BuildType=Debug`. It could show more info.

**Comment by coreybruce** [comment]
Here is the log from the debug version @deathkiller 

https://gist.github.com/coreybruce/547b4daeba8171ae0c7f4b388cbc74a0

**Comment by deathkiller** [comment]
You probably don't have files in right directories. You must copy `Content` directory from the repository to `./Content/` and original JJ2 files to `./Source/` directory. Then it should stop complain that `./Source/Anims.j2a` and the rest of files are missing. And do NOT use files from previous Jazz² Resurrection versions, this version uses different file formats.

**Comment by coreybruce** [comment]
Where do I get source? I don't have a folder of that on the original Jazz 2 GOG folder

**Comment by deathkiller** [comment]
Original Jazz 2 GOG folder is the `Source`. You have to copy all files from original Jazz 2 GOG folder to `./Source`.

**Comment by coreybruce** [comment]
ok so sound on the cutscene or menu music, the menu background is black and if I select a level the game crashes.

**Comment by coreybruce** [comment]
Hmm I do have that installed but here is my log

https://gist.github.com/coreybruce/35121ecee584ec15ae737873a452ced6

**Comment by coreybruce** [comment]
Ahh I see so more development is needed to get this working properly I assume?

**Comment by deathkiller** [comment]
No, Shareware Demo episode is already fully playable, so if you want to try Shareware Demo levels, you just need to put required files to right folders. If you want to try other episodes, you'll have to wait.

**Comment by coreybruce** [comment]
Ah I see so more works need to be done

**Comment by deathkiller** [comment]
I thought you just want to try to build it and run it. With latest changes it's possible to play the game till the end (but some objects/enemies are still missing, so some levels are almost empty).

**Comment by coreybruce** [comment]
Sorry forgot to reply, no I was wanting to play the full game but if it isn't ready to do that and only the demo than that's understandable

**Comment by deathkiller** [comment]
Ah, I probably misinterpret "wanted to join in and test it out even tho it is no ready" as you wrote a few posts earlier. Then this is not for you, it's more like a tech demo.
