### ISSUE TITLE
Linux version crashes during opening animation

### ISSUE THREAD

**Issue by shadowofdarkness** [deathkiller/jazz2-native#10]
I'm using the GOG version on Ubuntu 22.10 and the game crashes less then one second into the opening animation.

Terminal output https://pastebin.com/iPxeVj4P

**Comment by shadowofdarkness** [comment]
I found out the problem, it was due to case sensitivity in the file system.
The game provided Source/Rescue.j2e which then caused a error after the cache was created by the game trying to load Cache/Episodes/rescue.j2e

I manually renamed Rescue.j2e to rescue.j2e in the source directory and then the game loaded fine afterwards.

**Comment by deathkiller** [comment]
This shouldn't happen, all filenames should be already converted to lower-case in `Cache` directory, but maybe I've already fixed it, but not released yet.

**Comment by shadowofdarkness** [comment]
Just to note that I tested the new version by deleting the Cache directory and having Rescue.j2e named with the capital R and it still has the problem. So it was not just a problem with you not having a new enough release.

**Comment by deathkiller** [comment]
And terminal output is the same?

**Comment by shadowofdarkness** [comment]
Yes the output is the same

**Comment by deathkiller** [comment]
and if you delete `Cache` and then create `Cache` and `Cache/Episodes/` directories, will it work?

**Comment by shadowofdarkness** [comment]
That didn't work, still the same error.

**Comment by deathkiller** [comment]
Ah, yeah, you are right. It should be fixed in the latest commit. Directory was deleted, but it wasn't recreated afterwards.

**Comment by deathkiller** [comment]
You can download the lastest build from GitHub Actions here: https://github.com/deathkiller/jazz2-native/actions/runs/3423328665
