### ISSUE TITLE
-Wpedantic produces many warnings

### ISSUE THREAD

**Issue by Vitexus** [deathkiller/jazz2-native#12]
Fix warnings somehow to make build percentage shown well.

```
Sources/Jazz2/Actors/Enemies/Bosses/../../../UI/Alignment.h:24:34: warning: extra ‘;’ [-Wpedantic]
   24 |  DEFINE_ENUM_OPERATORS(Alignment);
      |                                  ^
```

**Comment by deathkiller** [comment]
Fixed. Removed some GCC flags.

**Comment by Vitexus** [comment]
There is really easy fix: strip the ; after DEFINE_ENUM_OPERATORS()
But the issue is closed thus i didn't sent my almost done patch here.

**Comment by deathkiller** [comment]
It's macro that should look like function call, so omitting semicolon doesn't make a sense. Also, only GCC complained about this.
I will probably add back some of the flags I removed later.
