### ISSUE TITLE
Broken using Shareware Demo

### ISSUE THREAD

**Issue by myself600** [deathkiller/jazz2-native#14]
**Demo source**: https://www.pukenukem.com/downloads/tsfdemo.exe

I've tried renaming files to lowercase (per https://github.com/deathkiller/jazz2-native/issues/10#issuecomment-1299524279), removing `~/.local/share/Jazz² Resurrection/Cache` folder and running release 1.2.0 (as that's what's currently used in http://deat.tk/jazz2/wasm/). Compiled with GCC 12.1.0 if that helps.

### Screenshots:

![jazz2_1](https://user-images.githubusercontent.com/3542623/204133670-9ca4f720-eb63-416b-bbe8-fbc23b4b72bf.gif)

![jazz2_2](https://user-images.githubusercontent.com/3542623/204133699-780b36ca-3ab1-4f3b-a2f7-42ab90dd5bbd.gif)

### Attachments:

[jazz2.log](https://github.com/deathkiller/jazz2-native/files/10098202/jazz2.log)

**Comment by deathkiller** [comment]
The Secret Files demo is not supported, only original JJ2 Shareware Demo is supported. TSF demo has different mapping of animations, that's why you can't see any objects.

**Comment by deathkiller** [comment]
Added error message of unsupported version in 9adff54

**Comment by myself600** [comment]
Fix at least the background, please. It needs `Easter3.j2l`, but it should (possibly) work without it.

I guess then _Lori_ is added simply by moving over the full `Anims.j2a` in http://deat.tk/jazz2/wasm/. Also, the _Play Shareware Demo_ option should appear by default if only the shareware data is available.

**Comment by deathkiller** [comment]
> Fix at least the background, please. It needs Easter3.j2l, but it should (possibly) work without it.

Fixed in 49bb290

> I guess then Lori is added simply by moving over the full Anims.j2a in http://deat.tk/jazz2/wasm/. Also, the Play Shareware Demo option should appear by default if only the shareware data is available.

Web version is working differently, it's precompiled for Shareware Demo. But I will think about it.
