### ISSUE TITLE
Hosting shareware data?

### ISSUE THREAD

**Issue by myself600** [deathkiller/jazz2-native#15]
It might be a good idea to host them on your website as it took me awhile to find the source (https://www.pukenukem.com/downloads/tsfdemo.exe, https://archive.org/download/JazzJackrabbit2Demo/J2swc123.exe), which files and which versions to use with the game and also unpacking them. It would be convenient to just download them (think of Android for example)

### Attachments:

[Games.zip](https://github.com/deathkiller/jazz2-native/files/10113273/Games.zip)

**Comment by deathkiller** [comment]
I'm hosting Shareware Demo on my website already, there are no links to it though. I'm still not sure if this will have any use, because Shareware Demo can be played directly in web browser and it's really short - less than 10 minutes if you are not trying to find all secrets.

**Comment by myself600** [comment]
It's good if you just want to try the game (similarly to what the Shareware Demo's purpose is for). It's better than just being greeted by a "place your game data" screen before you can actually play (assuming the game downloads them for you).

The web port is too slow for me to play.

**Comment by deathkiller** [comment]
Yeah, but 99% of players want to play full game, not just only 10 minutes demo, that's why there is "place your game data" screen and if you press Enter, directory will be opened in your file manager, you just copy it there and that's it. Downloading Shareware Demo automatically would be confusing (actually it was already there and it was confusing), because it would copy there some files itself and you would have to delete them before copying your own.

> The web port is too slow for me to play. Also, the game data's in a custom format.

What do you mean by `"the game data's in a custom format"`?

**Comment by myself600** [comment]
OK, I just think it's better to go with the web port approach (for that 1%) and then allow the player to add more content. The shareware data is identical checksum-wise with the full version, except for AnimsSw.j2a.

> What do you mean by `"the game data's in a custom format"`?

Missing header of http://deat.wz.cz/jazz2/jazz2.data

**Comment by deathkiller** [comment]
> I just think it's better to go with the web port approach

That's not possible, web version is working differently. I can't do the same on other platforms.

> The shareware data is identical checksum-wise with the full version, except for AnimsSw.j2a.

That's right, but `AnimsSw.j2a` file is the biggest one, it contains all animations and audio samples and currently it's extracted to `Cache` directory for faster subsequest startup. I have already some other issues with this file, let's not add more please.

> Missing header of http://deat.wz.cz/jazz2/jazz2.data

Missing header? It's working well, isn't it? The file is result of Emscripten compilation, it's not my file format and it's not meant to be downloaded.

**Comment by myself600** [comment]
> That's not possible, web version is working differently. I can't do the same on other platforms.

I already did that in jazz2-git AUR package after first implementing this in opentitus. This was just a suggestion to go with a more upstream approach.

> Missing header? It's working well, isn't it? The file is result of Emscripten compilation, it's not my file format and it's not meant to be downloaded.

I was assuming this is the case, but was pointing out that it's not reusable outside the webpage.
