### ISSUE TITLE
Feature Request: Show highlighted weapon's name in Weapon Wheel.

### ISSUE THREAD

**Issue by Shockwave508** [deathkiller/jazz2-native#17]
Regarding Jazz 2, the existing spinning ammo icons generally don't hint at what the weapon is and/or does. Would it be possible to add a text string just below the weapon wheel, which will display the name of the currently-highlighted weapon, as long as the weapon wheel is visible on-screen?

**Comment by deathkiller** [comment]
Added ammo count as option in https://github.com/deathkiller/jazz2-native/commit/f25a387be5e73a1671bc99cbef63be19ca6aeea7.
