### ISSUE TITLE
Base package requirements not clear in running the application instructions.

### ISSUE THREAD

**Issue by SissiHermanni** [deathkiller/jazz2-native#19]
* Install dependencies: sudo apt install **libglew2.2** libglfw3 libopenal1 libopenmpt0
    * Alternatively, **install provided .deb or .rpm package and dependencies should be installed automatically.**

I think it's worth adding that installing the game on an Ubuntu-based operating system requires Ubuntu Jammy as base package, because Bionic and Focal doesn't have and can't have libglew2.2. 

Bionic has version 2.0 (supported until 2023) and Focal has version 2.1 (supported until 2025). 
If you try install game with .deb in Focal or Bionic it will warn you that the dependencies cannot be met and refuses to install.
This also applies to the portable Linux version.

If you can compile .deb file in Ubuntu Bionic as base package you also have forward compatibility for Focal and Jammy.

**Comment by deathkiller** [comment]
`ubuntu-18.04` GitHub Runner is deprecated and I would like to keep using `ubuntu-latest`. So should I replace `libglew2.2` with `libglew2.0`? I'm not really familiar with this, so I'll take suggestions.

**Comment by myself600** [comment]
It is necessary to use older dependencies (thus building on older distros) when supporting older GNU/Linux systems via native packages. Launchpad builds them for each distro separately, making it possible to use the latest dependencies provided by the OS. There are other ways tho, if you want to bundle dependencies, most notably Appimages and other distribution formats including Snaps or Flatpaks that includes dependencies bundled at the cost of binary size. Another way is static compilation (e.g. https://johnvansickle.com/ffmpeg/) or shipping the libraries alongside binaries (like on Windows), also universal installers come to mind (those with the `.run` extension - Virtualbox, Nvidia drivers).

Packages should usually be built for OS releases that are still maintained upstream (in this case, those colored yellow and green here: https://en.wikipedia.org/wiki/Ubuntu#Releases). Practicality is more important, except when features and security updates are involved. So I would say, target the oldest (yellow colored) Ubuntu (18.04 is quickly reaching EOL so you might want to skip that as you said) and its dependencies if you want to universally support multiple releases at once or try to bundle them statically.

**Comment by deathkiller** [comment]
I changed GLEW to 2.1 and it seems I can't run it on Ubuntu 22 anymore, because there is no GLEW 2.1, only GLEW 2.2. So any suggestions before I roll it back? Is static linking of GLEW the only way?

Also Flatpak and Appimage as another option could be great, but I don't know how to build them.

**Comment by myself600** [comment]
> I changed GLEW to 2.1 and it seems I can't run it on Ubuntu 22 anymore, because there is no GLEW 2.1, only GLEW 2.2. So any suggestions before I roll it back? Is static linking of GLEW the only way?

Probably. Makes sense as compiled binaries tend to require specific versions of libraries. Maybe include a separate static workflow? You can also strip the binary and compress it using UPX.

**Comment by deathkiller** [comment]
OK, I changed Linux build to use static GLEW, so it should work correctly now. I wonder if binary is already stripped or not. Windows version is stripped. I would like to avoid UPX, binaries are not that big.

**Comment by deathkiller** [comment]
So I have to build it directly on corresponding OS version, right? Is there any other way?

`ubuntu-18.04` runner is already deprecated, so it can be removed anytime and it will probably be very soon. I can add workflow with `ubuntu-20.04` if you need it though.

**Comment by deathkiller** [comment]
I added https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml with `ubuntu-18.04`. Also, I disabled GLEW for Linux builds, because it seems it's not needed there. Everything should be fine now.

**Comment by deathkiller** [comment]
Send me log from terminal and also try both SDL and GLFW versions.

**Comment by deathkiller** [comment]
It seems there is nothing wrong in the log. I can try it myself, but it's probably some bug in GLFW library (and also it could be already fixed in newer versions). Just use the SDL version if it works for you.

**Comment by maze88** [comment]
I'm experiencing the same issue (on Debian 11).
I read the comments but didn't quite understand how to solve it...

Running `$ jazz2` returns:
```
jazz2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by jazz2)
jazz2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by jazz2)
jazz2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by jazz2)
```

**Comment by deathkiller** [comment]
It seems the binary is not compatible with your system. You can try to download build for older Linux versions - https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml [in GitHub Actions > **Linux (Legacy)**] - or build the game yourself. Distributed binaries are precompiled on the latest ubuntu and because it's Linux, there are compatibility issues when you try to run it on different/older OS versions.

**Comment by maze88** [comment]
Thanks Dan, that did the trick! (:

**Comment by deathkiller** [comment]
That's great. You're welcome!
