### ISSUE TITLE
Have the FMV Cutscenes played at the correct aspect ratio (4:3)

### ISSUE THREAD

**Issue by MetalNeon** [deathkiller/jazz2-native#21]
I really enjoy this project, but noticed there was an issue. The cutscenes for the game currently are stretched to the aspect ratio of the screen as opposed to playing in the original ratio of 4:3. I was wondering if there was something that could be done about this for the cutscenes in particular.

**Comment by deathkiller** [comment]
This is not entirely true and it's intentional. If you try to resize the window, you will see it tries to dynamically adjust aspect ratio. The range is from 4:3 to 16:9.44. If it's out of dynamic range, then it will zoom in or zoom out, so you will not see black bars in most cases and it looks good enough on wide screens.

> I was wondering if there was something that could be done about this for the cutscenes in particular.

Do you have any specific suggestions for this?

**Comment by MetalNeon** [comment]
So after taking a quick glance at what you were saying, it appears that  it does letterbox the cutscenes if you're playing at an aspect ratio smaller than 4:3, but it appears that it doesn't actually stretch the FMV, but rather crops off the top and bottom of it. 
![Jazz2_z6CTPRHQpW](https://user-images.githubusercontent.com/83677306/209957030-3a8c38c5-cd3d-44d5-bd55-560e55c2f1c8.png)
![Jazz2_muybPjoq6u](https://user-images.githubusercontent.com/83677306/209957057-a40afaf3-c9a4-431c-a7be-c6e24f379004.png)
These aren't the best showcases but it's what I could nab.
I'd advise that instead of cropping the top and bottom of the FMV off that instead it's pillarboxed (add black bars to the left and right edges of the screen) to the correct aspect ratio.

**Comment by deathkiller** [comment]
I don't know what to do with it because I prefer it the way it is now, so I'll probably have to add a switch to Options.

**Comment by deathkiller** [comment]
Added *Keep Aspect Ratio In Cinematics* to Options in https://github.com/deathkiller/jazz2-native/commit/ea55eed3a1ad0d84dc3932d99fc52ad9a71dce58.
