### ISSUE TITLE
Graphical Glitches on intel iMac

### ISSUE THREAD

**Issue by ckrokosh** [deathkiller/jazz2-native#22]
I am running the GOG version of Jazz Jackrabbit 2 on a 27inch intel mid 2015 iMac with an AMD RADEON M395.  The game runs super smooth but there appears to be gaps between some of the sprite tiles. I attached a screen shot. Note just below Jazz and to the left of him. This is a stationary shot but it is much more evident while the game is running. This happens on the web version as well as all the downloaded versions I tried. I tried version 1.4 (SDL and the 2nd one included in the download) and I also tried the latest ones from the "Actions" and it happens on both.  I thought it might be a vsync issue. I noticed on the help page there were switches for vsync but these don't appear to work on a Mac. Let me know if you require any further information.
<img width="1920" alt="Screen Shot 2023-01-01 at 23 07 45" src="https://user-images.githubusercontent.com/4911451/210203390-61fbe948-c2c4-4686-b336-d93f4e6321fc.png">

**Comment by deathkiller** [comment]
It's caused by different rasterization of your GPU. I can't reproduce it on my GPU (NVIDIA GeForce 2070), but on AMD it probably rasterizes it differently and makes these artifacts. I don't know how to fix it, I don't even have AMD GPU. You can try to resize the window, it sometimes fixes the problem.

**Comment by myself600** [comment]
Try in maximized window mode as that's what I'm doing to workaround this issue

**Comment by ckrokosh** [comment]
Thanks. Maximizing the window resolved it.
