### ISSUE TITLE
Passing arguments to macOS version

### ISSUE THREAD

**Issue by genericmilk** [deathkiller/jazz2-native#27]
Hi there!

First of all, WOW. This game was my childhood and I've fond memories of playing it with my siblings, I gave them both a message when I stumbled across your project and was blown away by your phenomenal work!

I note that you have a startup argument system for cheats. I've been looking to enable them to get past a softlocked level as it won't proceed (Boss never spawns), But the arguments seem Windows oriented `/cheats` and `/cheats-unlock`

I'm using an M1 Pro Macbook and while trying to execute the binary directly with arguments `/Applications/Jazz² Resurrection.app/Contents/MacOS/Jazz²\ Resurrection /cheats` the application seems to ignore it, I presume because the argument style is Windows oriented and not traditionally MacOS oriented (ie `--cheats` etc).

Is this something I  am doing wrong? Or something I can patch into the Jazz2.config file?

All my best and again, thank you. This is seriously one of my favourite OSS finds ever.

**Comment by deathkiller** [comment]
Hi, I'm glad you like it.

I think this is a bug and hopefully it should be fixed now. Can you try it again with the [experimental build](http://deat.tk/jazz2/?experimental)? Arguments look Windows-oriented, but it should work fine also on other platforms.

By the way, are you using ARM64 version? This version hasn't been tested yet, because I don't have any M1/M2 device, so I wonder if it works.

**Comment by genericmilk** [comment]
Fab thanks so much! I've downloaded the latest and that's done the job.

I am using ARM64 version. Performance is so far so good, Couple of super minor graphical issues but nothing game breaking
<img width="1800" alt="Screenshot 2023-02-19 at 18 31 03" src="https://user-images.githubusercontent.com/1846127/219967896-3f2643d5-dca1-4d21-bfa9-0f2e942014ba.png">

Only issue that did stop me in my tracks was the boss for "Loose Screws" (Robot) not spawning in, hence the need to jjnext to the next one where needed. 

Again, thank you so much, I seriously appreciate the time spent!

**Comment by deathkiller** [comment]
Great!

The Loose Screws Robot boss should be already fixed in v1.7.0.

These graphical issues can be usually fixed by resizing the window or turning on fullscreen in Options, but I haven't managed to figure out how to fix it completely.
