### ISSUE TITLE
DualSense controller doesn't work correctly on Android (but Xbox controller does)

### ISSUE THREAD

**Issue by Calinou** [deathkiller/jazz2-native#28]
**Jazz² Resurrection version:** 1.7.0
**Device:** Samsung Galaxy Z Fold4, Android 13.0

When I connect a Xbox One V4 controller via Bluetooth, everything works perfectly. However, when I connect a DualSense controller instead, there are several issues:

- D-pad up is ineffective in the menus and game.
- Player always moves to the left during gameplay. This issue doesn't occur in menus. Maybe this is due to incorrect axis binding, making the game think the left stick is being pressed towards the left constantly.
- Can't use analog sticks for player movement instead of the D-pad. I prefer using the analog stick as I find it more reliable, since D-pads are often mushy (and don't always register presses) on most gamepads.

I assume [controller mappings](https://github.com/deathkiller/jazz2-native/blob/master/Sources/nCine/Input/JoyMappingDb.h) are incorrect or missing. Maybe they could be synced with the latest version of https://github.com/godotengine/godot/blob/master/core/input/gamecontrollerdb.txt?

For reference, my DualSense's GUID is `030000004c050000e60c000011810000` on Linux (not sure if it's different on Android).

**Comment by deathkiller** [comment]
Can you send me log file from `/­­Android/­­data/­­jazz2.­­resurrection/­­files/­Jazz2.­log`, please? It should contain detected gamepads and its GUIDs. GUIDs could be different on Android. Also, it uses custom parsing on Android, so something could be wrong, but I think someone already had similar issue with different gamepad because of wrong mappings.

I'm using shorter mapping DB from SDL2 sources, because it's usually enough, smaller and faster to parse, but maybe I could add more mappings. Another option would be to allow loading of custom mappings from user supplied file (it's already supported on some platforms, but probably disabled on Android).

**Comment by deathkiller** [comment]
I see the detected GUID (`050000004c050000e60c0000ffff3f00`) in the DB already (https://github.com/deathkiller/jazz2-native/blob/master/Sources/nCine/Input/JoyMappingDb.h#L922), but for some reason it's not detected. Also, detected axis ranges are strange. I will take a look why this is happening.

**Comment by deathkiller** [comment]
I fixed the gamepad detection in https://github.com/deathkiller/jazz2-native/commit/8e474e0c773104f0b0af5617b55f65d3b15fe3a2. Can you try the latest experimental build?

**Comment by Calinou** [comment]
> I fixed the gamepad detection in [8e474e0](https://github.com/deathkiller/jazz2-native/commit/8e474e0c773104f0b0af5617b55f65d3b15fe3a2). Can you try the latest experimental build?

I've tried the latest experimental build, but it crashes whenever a controller input is detected. The game works normally if no controller is connected.

**Comment by deathkiller** [comment]
That's strange. I did some changes, can you try it again, please?

**Comment by Calinou** [comment]
> That's strange. I did some changes, can you try it again, please?

I've tried with the latest experimental APK and while I no longer get a crash, gamepad mapping is incorrect like in the original report (D-pad up not working, player moving to the left if not pressing right).

**Comment by deathkiller** [comment]
That's strange. I added input diagnostics in the latest build (in Options > Controls > Input Diagnostics). You can use it to see axis values and button states and hopefully see what's wrong with the mapping. Raw State is what gamepad returns and Mapped State is what game sees. All mapped axes should be (around) zero if you are not touching anything, and its range should be from -1.0 to 1.0. The axis you're interested in is LX.

**Comment by Calinou** [comment]
> That's strange. I added input diagnostics in the latest build (in Options > Controls > Input Diagnostics). You can use it to see axis values and button states and hopefully see what's wrong with the mapping. Raw State is what gamepad returns and Mapped State is what game sees. All mapped axes should be (around) zero if you are not touching anything, and its range should be from -1.0 to 1.0. The axis you're interested in is LX.

LX and LY always remain `-1.0`, even if I move the left stick. RX/RY/LT/RT correctly change if I move the right stick or triggers though.

**Comment by deathkiller** [comment]
I need also corresponding values from Raw State to be able to normalize it properly or to check why it stays on -1.0. Ideally, the minimum, maximum and center value, and also ID (`a0`, `a1`, `a2`, ...) of raw axis for LX and LY.

**Comment by deathkiller** [comment]
I need values of the left analog stick when you are moving it. Ideally, the minimum, maximum and center value - when you move it to the left, right and center, etc. Otherwise, I don't know what to do. Currently it seems to me there is something wrong with the gamepad.

**Comment by Calinou** [comment]
> I need values of the left analog stick when you are moving it. Ideally, the minimum, maximum and center value - when you move it to the left, right and center, etc. Otherwise, I don't know what to do. Currently it seems to me there is something wrong with the gamepad.

Moving the left stick doesn't change the `a0` and `a1` raw values at all. Moving the right stick and triggers affects `a2`, `a3`, `a4`, `a5`, `a6` and `a7` as expected.

**Comment by deathkiller** [comment]
So no axis values are changed when the left stick is moved? If the gamepad is returning no/wrong values, then I can't fix it unfortunately. And the other gamepads work fine.

**Comment by Calinou** [comment]
> So no axis values are changed when the left stick is moved? If the gamepad is returning no/wrong values, then I can't fix it unfortunately. And the other gamepads work fine.

Indeed, the value remains `-1.00` for both axes regardless of which direction I move the left stick in.

I've also tried connecting the DualSense via USB-C instead of Bluetooth, but I get the same result.

**Comment by PongWithBreakout** [comment]
Hello, I see that this issue is not resolved.
It's possible that it's not the game that's messed up, but the keylayout for Dualsense. @Calinou Have you checked inputs with Gamepad Tester?

**Comment by Calinou** [comment]
>  @Calinou Have you checked inputs with Gamepad Tester?

I've tested on the Android device and can confirm inputs work correctly on https://hardwaretester.com/gamepad.

**Comment by deathkiller** [comment]
Similar issue (https://github.com/deathkiller/jazz2/issues/132) was fixed in commit https://github.com/deathkiller/jazz2-native/commit/c964c7dda2701887bd4822824dec5d2494736883. This issue is probably fixed as well.
