### ISSUE TITLE
Opening cutscene is missing the sound effects

### ISSUE THREAD

**Issue by kode54** [deathkiller/jazz2-native#32]
### Jazz² Resurrection version

2.0.0

### System information

macOS Sonoma beta 3, 2020 Mac mini

### Issue description

The opening cinematic appears to have its correct sequenced music file playing, but is missing all of the scripted sound effects which play throughout.

### Steps to reproduce

1. Download Jazz Jackrabbit 2: The Christmas Chronicles from my GOG games page.
2. Extract using macsourceports.com's Extractor tool
3. Create the game files directory and copy the (installer)\app folder contents to it
4. Launch the game executable with iTerm because I cannot get the .app bundle to launch, even after xattr -cr'ing it.
5. Game launches, cinematic plays with music but no sound effects.
6. Main menu has the usual random sound effects.

**Comment by deathkiller** [comment]
Cinematics SFX are not implemented yet and it has very low priority for me, because 99% of people just skip it anyway.

**Comment by deathkiller** [comment]
Implemented in commit https://github.com/deathkiller/jazz2-native/commit/583d0991f048b0ac5801a9740037060f84f73fdd.
