### ISSUE TITLE
"Save & exit" doesn't save the game progress on Android

### ISSUE THREAD

**Issue by vardecab** [deathkiller/jazz2-native#33]
### Jazz² Resurrection version

Android app 2.1.0 & source files JJ2SF 1.24

### System information

Android 13

### Issue description

Hi :) 

First of all, kudos for great work on this — works really well on Android! 

On PC you can save the game in any point in time, give it a name and then load it on the next run. I don't see this in Android version. You can "Save & exit" when playing but it doesn't save anything and there is no way to load that save afterwards. 

### Steps to reproduce

1. Open the game
2. Play story 
3. Select character & difficulty level 
4. Start playing 
5. Hit a corner to show options 
6. Save & exit
7. Close the game
8. Open the game
9. Nothing — there is no option to load the game, just start a new one or play a chapter. Starting a new game starts it from scratch.

**Comment by deathkiller** [comment]
Hi, thank you!

It automatically saves state on the beginning of each level, then you can just open the last episode and it will continue in this level (training level is an exception, you have to complete also the level after it).

Unfortunately, Jazz² Resurrection can't save game in the middle of a level (as it worked in the original game) on any platform, only automatic saving on the beginning works.

See https://github.com/deathkiller/jazz2/issues/71 and https://github.com/deathkiller/jazz2/issues/48 for more information.
