### ISSUE TITLE
Building for older macOS

### ISSUE THREAD

**Issue by weijiangan** [deathkiller/jazz2-native#34]
### Jazz² Resurrection version

1.7.0

### Problem or limitation

Currently the macOS build only supports macOS 12.6+, I'm still on macOS 11 because my MacBook Pro 11,3 cannot be upgraded to newer OSes. Would be nice to have a way to build for older Macs

### Proposed solution

Maybe expose a way to let us bring our own dependencies or library? I see that the library files are compiled in a certain way... Maybe you share the build script?

**Comment by deathkiller** [comment]
You can already use your own dependencies - set CMake variable `NCINE_DOWNLOAD_DEPENDENCIES` to `OFF`, then copy your dependencies to `Libs/` directory (or set `NCINE_LIBS` variable to your path).
The core dependencies for macOS are built here: https://github.com/deathkiller/nCine-libraries.

Unfortunately, I don't own any Apple devices, but I thought it should work automatically on older versions. I don't know how to make it work on older Macs.

**Comment by deathkiller** [comment]
Closed due to inactivity.
