### ISSUE TITLE
opengl won't allow it to start

### ISSUE THREAD

**Issue by FrostKnight** [deathkiller/jazz2-native#36]
### Jazz² Resurrection version

2.1 possibly others. 1.91 and 2.0 also

### System information

Hyperbola Intel HD Graphics 4000

### Issue description

I get this issue when I try to type in ./jazz2 after chmod +x has been applied to your linux version.

/home/localuser/.local/share/Jazz² Resurrection/Update/jazz2: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

Ironic thing is, I have opengl unless your thinking of a specific opengl version that I don't have.

I haven't yet added the files needed to start the game yet, but I am fully aware if that the above shared library issue would come up now rather than later.

Btw, Hyperbola is based on Arch and is focused on stability and security so it uses debian patches currently.

### Steps to reproduce

1: downloaded the linux binary, 
2: extracted it, 
3: went into the folder its in, 
4: chmod +x jazz2 
5: Then I typed in terminal ./jazz2 and viola that bug came up.

**Comment by deathkiller** [comment]
You can try to build the game yourself. Otherwise, I don't know how to help you unfortunately. It probably have to be linked to different OpenGL library on your system. That's a disadvantage of Linux where you can't usually create universal binary that will work on all distros and versions.

**Comment by FrostKnight** [comment]
> You can try to build the game yourself. Otherwise, I don't know how to help you unfortunately. It probably have to be linked to different OpenGL library on your system. That's a disadvantage of Linux where you can't usually create universal binary that will work on all distros and versions.

I tried installing libglvnd from archlinux, seems to fix the issue but I do have one other separate issue regarding glibc now. Apparently my version is too old for this to work with. I have the version 2.3.0 not 2.3.2.

I am not sure if this is deliberate or not, but older versions are blocked.

**Comment by deathkiller** [comment]
Which older versions? If you build it yourself, it should link to your local glibc version.
Also, you can try [**Linux (Legacy)** build](https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml) on GitHub Actions which is built on older Ubuntu and should link to older libraries.

**Comment by FrostKnight** [comment]
> Which older versions? If you build it yourself, it should link to your local glibc version. Also, you can try [**Linux (Legacy)** build](https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml) on GitHub Actions which is built on older Ubuntu and should link to older libraries.

How do I download the legacy version?

**Comment by deathkiller** [comment]
Click on the link - https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml, then click on the latest workflow and download artifact at the bottom of the page.

**Comment by FrostKnight** [comment]
> Click on the link - https://github.com/deathkiller/jazz2-native/actions/workflows/linux_legacy.yml, then click on the latest workflow and download artifact at the bottom of the page.

I saw thank you, my bad for asking. But I edited my reply to show compiling error.

**Comment by deathkiller** [comment]
Interesting, you probably have some older version of compiler, because all builds are passing on GitHub.

Unfortunately, OpenGL 3.0 is required which is already 15 years old, it's not any new. And it usually works, I've never heard of such problems.

**Comment by FrostKnight** [comment]
> Interesting, you probably have some older version of compiler, because all builds are passing on GitHub.
> 
> Unfortunately, OpenGL 3.0 is required which is already 15 years old, it's not any new. And it usually works, I've never heard of such problems.

My compilter is gcc 8.4.0 

Is this an issue?

I have tried libgl and libglvnd each on their own.

libglvnd requires glibc 3.4 alas... as far as I can see anyhow. So i cant use that.

However, I might be able to make it work if and this is a big if:

If I can compile it with the gcc version I have.

mesa-libgl is what I meant by libgl btw.

**Comment by deathkiller** [comment]
GitHub builds are using GCC 9.4.0 (the legacy one) and GCC 11.4.0 (the newest one). And CMake should find the best suitable OpenGL library on your system during build. But I don't use Linux myself, so hard to tell.

**Comment by FrostKnight** [comment]
> GitHub builds are using GCC 9.4.0 (the legacy one) and GCC 11.4.0 (the newest one). And CMake should find the best suitable OpenGL library on your system during build. But I don't use Linux myself, so hard to tell.

Ahhh I see... that explains a lot.

Hmm... alright. Well now I know then. ;)

**Comment by FrostKnight** [comment]
> GitHub builds are using GCC 9.4.0 (the legacy one) and GCC 11.4.0 (the newest one). And CMake should find the best suitable OpenGL library on your system during build. But I don't use Linux myself, so hard to tell.

Quick thought, do you think appimages would be able to bypass this issue and make it usable regardless? Just curious, if not then perhaps close this thread.

**Comment by deathkiller** [comment]
I have no idea, I don't know how appimages work nor how to create them.

**Comment by FrostKnight** [comment]
> I have no idea, I don't know how appimages work nor how to create them.

Alrighty then. Nevermind, I'll lock it since, for the time being its not a huge thing. Maybe I will use jazz2 in a vm or my other drive for now. ;)

**Comment by deathkiller** [comment]
I lowered compiler requirements from C++20 to C++17, so it could be buildable on older GCC versions now.

**Comment by FrostKnight** [comment]
> I lowered compiler requirements from C++20 to C++17, so it could be buildable on older GCC versions now.

Its playable! Only one small issue exists still, one of the key buttons doesn't work when I start it. its usually either down or up. Weird right? I am not sure what causes this though.

**Comment by deathkiller** [comment]
*SynPS/2 Synaptics TouchPad* was detected as gamepad (it's happening for some mice on Linux, I don't know why), so I added it to blacklist now. It may have solved your problems.

**Comment by FrostKnight** [comment]
> _SynPS/2 Synaptics TouchPad_ was detected as gamepad (it's happening for some mice on Linux, I don't know why), so I added it to blacklist now. It may have solved your problems.

The ironic part is, I disabled my touchpad...

I have a trackpoint that I use for movement instead. ;)

**Comment by deathkiller** [comment]
Great, you're welcome! I had the same problem with Razer mouse and keyboard already. SDL2 detects them as joysticks on Linux, so it's assigned to the first slot and it just causes problems.

**Comment by FrostKnight** [comment]
> Great, you're welcome! I had the same problem with Razer mouse and keyboard already. SDL2 detects them as joysticks on Linux, so it's assigned to the first slot and it just causes problems.

Btw, you nicer than some devs on here, regarding gcc, etc... I wish I knew how to push back the dependency of gcc on other stuff with unneeded requirements.

That being said, unrelated, but do you know when multiplayer support will return? I am curious to see what that will look like.

**Comment by deathkiller** [comment]
Thanks! You may have noticed that 2 commits with multiplayer support are already there, players can run around the map, but everything else is still missing, so it's disabled during compilation for now. It's a lot of work, so I can't tell when it will be complete, but some progress is there.

**Comment by FrostKnight** [comment]
> Thanks! You may have noticed that 2 commits with multiplayer support are already there, players can run around the map, but everything else is still missing, so it's disabled during compilation for now. It's a lot of work, so I can't tell when it will be complete, but some progress is there.

Hmm... I see, well fair point. Tell me when its ready, I have interest.
