### ISSUE TITLE
build broken on OpenSuse Leap 15.4 (gcc-13)

### ISSUE THREAD

**Issue by bog2k3** [deathkiller/jazz2-native#40]
### Jazz² Resurrection version

2.3.0

### System information

Linux OpenSuse Leap 15.4 gcc-13

### Issue description

Attempting to build from source produces the following error:
```
c++: error: unrecognized command line option ‘-Wpessimizing-move’
c++: error: unrecognized command line option ‘-Wredundant-move’; did you mean ‘-Wredundant-decls’?
```
The flags were added to the cmake/ncine_compiler_options.cmake file in the commit 9d0afff397a033940ca8ed63994e1b12896c815

Removing the flags manually from the file fixes the build.

### Steps to reproduce

git clone https://github.com/deathkiller/jazz2-native
cd jazz2-native
mkdir build && cd build

**Comment by mnhauke** [comment]
openSUSE 15.4 ships multiple versions of gcc ...
* gcc 7.5.0+r278197
* gcc 8.2.1+r264010
* gcc 9.3.1+git1296
* gcc 10.4.0+git2794
* gcc 11.3.0+git1637
* gcc 12.3.0+git1204
* gcc 13.2.1+git7813

openSUSE Leap 15.4 uses gcc  7.5.0 by default.
You can check this via `gcc -v`

The mentioned  g++ warnings were [introduced](https://gcc.gnu.org/gcc-9/changes.html) with gcc9  so you have to use a gcc version >= 9 for the compilation of jazz2-native.

To use the a newer version of gcc you have to install the new gcc version first and then tell the buildsystem where to find the compiler that should be used for compilation:
e.g. gcc13
```
sudo zypper install gcc13 gcc13-c++
export CC="gcc-13"
export CXX="g++-13"
```
Then follow the usual compilation steps.

Is there a specific reason why you don't use the ready made package from the OBS games repository ?
https://build.opensuse.org/package/show/games/jazz2
https://build.opensuse.org/package/view_file/games/jazz2/jazz2.spec?expand=1

btw: openSUSE 15.4 is nearly end of life ...
https://lists.opensuse.org/archives/list/announce@lists.opensuse.org/message/FVYHTTP5WIFGCEABUXKKODTYZUVWIDPI/

**Comment by deathkiller** [comment]
I removed them now in commit https://github.com/deathkiller/jazz2-native/commit/969e00d45e01e1077884207717e009bd81862177. I thought that unsupported `-W` arguments will be skipped automatically (without any errors) and I didn't know that these ones were added later in GCC9.
