### ISSUE TITLE
Assigning multiple controller buttons to the same action

### ISSUE THREAD

**Issue by bviktor** [deathkiller/jazz2-native#46]
### Jazz² Resurrection version

2.4.1

### Problem or limitation

Example: I'd like to assign both LT and RT to fire, and LB and RB to jump. Currently I'm not finding a way to achieve this.

I tried to use AntiMicroX, unfortunately some hardcoded built-in mappings conflict with it, e.g. B will always be "Enter" internally, and I've tried to set it to "Esc" in AMX, so it actually presses those same buttons simultaneously.

### Proposed solution

It'd be great if there was a way to either

1) allow us to disable internal controller support in Jazz2 so that I can manually set up keyboard mappings in 3rd party programs like AMX, which would send my controller button pushes as keyboard keystrokes to the game
2) allow us to set up multiple mappings for the same actions, much like for keyboard, i.e. "key 1" and "key 2" in controller options.

Thanks a lot.

**Comment by deathkiller** [comment]
Hi,

> allow us to disable internal controller support in Jazz2

You can disable it already if you delete all assignments in Controls options using Delete key.
More options for controls assignment are planned, but I don't know when it will be done.

**Comment by deathkiller** [comment]
Input handling reworked in commit https://github.com/deathkiller/jazz2-native/commit/367c6123ce0abb8960cb1909d89855be600fefac. Added possibility to assign up to 6 bindings (keys, buttons or axes) to any action.

**Comment by bviktor** [comment]
Sorry for the late response, but awesome, seems to work well! Thanks a bunch!
