### ISSUE TITLE
Support small screen

### ISSUE THREAD

**Issue by mtojek** [deathkiller/jazz2-native#57]
### Jazz² Resurrection version

1fb7dff45e177ed115aceb85c20df580d38cceca

### System information

Debian bookworm/OrangePi/TFT LCD

### Issue description

Hi,

I'm running Jazz2 on OrangePi with 3.2 TFT LCD (320x240), and I can see some scaling problems. The game screen seems to be fine, but we may need to adjust the menu screen in this resolution.

![439972637_468706262499253_4941977076122644290_n](https://github.com/deathkiller/jazz2-native/assets/14044910/f0ae78d0-57e0-4a8a-98ee-9d6c9e67708e)
![441988703_2358035571068932_6885069298036256711_n](https://github.com/deathkiller/jazz2-native/assets/14044910/dba3a5a2-d74d-475f-afb9-25382ed215e9)
![441347537_1862412307505065_3782654606326197277_n](https://github.com/deathkiller/jazz2-native/assets/14044910/77a82c87-590f-4a7a-a39e-eb622b2425c1)
![441885532_1501347417188628_7622358244565138269_n](https://github.com/deathkiller/jazz2-native/assets/14044910/0e562e2c-3b3e-4629-b6e6-75de83fd0820)
![441292310_732418985749417_1227710346822573427_n](https://github.com/deathkiller/jazz2-native/assets/14044910/8d55e4c4-5221-46d6-aa5e-e5f6fbb8aa8f)
![441894394_821575372694973_5274387879374835618_n](https://github.com/deathkiller/jazz2-native/assets/14044910/f1ee30ff-8146-48ce-bd3d-51641000152e)

### Steps to reproduce

Run the game.

**Comment by deathkiller** [comment]
I adjusted some of the menus. Please let me know what do you think. Then I will continue with some other sections.

**Comment by mtojek** [comment]
Hi @deathkiller!

Thanks for all adjustments, it fits better now:

 ![438158367_997467788442555_5457803967270130469_n](https://github.com/deathkiller/jazz2-native/assets/14044910/ae03bcbc-dea1-4463-9d44-a875e724e1fa)
![441006767_1400099813961926_980149070422525332_n](https://github.com/deathkiller/jazz2-native/assets/14044910/00c20639-adf4-4433-94d0-a26cf476c3b8)

I believe there might be a gentle improvement applied to in-game hints:

![438158244_1755109078225900_4526861258815439992_n](https://github.com/deathkiller/jazz2-native/assets/14044910/63e09f27-c152-426f-9fd1-c82e7f59d55a)

BTW Is it possible to scale the viewport? I'd like to see more and have a smaller hero :)

**Comment by deathkiller** [comment]
I made some more adjustments - the hint text and some menus.
Unfortunately, viewport scaling is broken and cannot be used at this moment.

**Comment by mtojek** [comment]
It is correct now! I will play a bit and see if I encounter other issues.

![442020496_1227200685086554_6651893945482296485_n](https://github.com/deathkiller/jazz2-native/assets/14044910/344bf9b2-08a2-4ad7-904f-d36440e7594a)

> Unfortunately, viewport scaling is broken and cannot be used at this moment.

I see! Maybe one day :)

**Comment by deathkiller** [comment]
I did some other small adjustments in recently released v2.7.0. And that's probably all for now, so I'm closing this issue. Feel free to re-open if needed. Viewport scaling would be done in the future if I manage to fix it one day, but it's not so easy, so it has lower priority.
