### ISSUE TITLE
Android crashes after opening cinematic 

### ISSUE THREAD

**Issue by Fancy2209** [deathkiller/jazz2-native#7]
GOG version, game crashes after the intro video, what do I do?

**Comment by deathkiller** [comment]
What is your device? You probably should be able to see some error message in Android logcat.

**Comment by Fancy2209** [comment]
> What is your device? You probably should be able to see some error message in Android logcat. 

My device is a Blackview BV6300Pro
I will grab the logcat when I can

**Comment by deathkiller** [comment]
Closed due to inactivity.

**Comment by Fancy2209** [comment]
I'm really sorry i will get the things when I can
School just hasn't let me have time to

**Comment by deathkiller** [comment]
No problem. You can now see the log in `/­­Android/­­data/­­jazz2.­­resurrection/­­files/­Jazz2.­log` in the latest version, logcat is not required anymore.

**Comment by deathkiller** [comment]
Hm.. that's very short. Can you try it again with the latest version from GitHub Actions? https://github.com/deathkiller/jazz2-native/actions/workflows/android.yml

**Comment by Fancy2209** [comment]
On the logcat I made just before that it seemed to be something related to MaliGPU's
Would you like I send that log?

**Comment by deathkiller** [comment]
Yes, that could be helpful.

**Comment by Fancy2209** [comment]
[JAZZ2.LOG](https://github.com/deathkiller/jazz2-native/files/10122401/JAZZ2.LOG)
This should be it

**Comment by deathkiller** [comment]
I can't see any meaningful error here

**Comment by deathkiller** [comment]
Can you test it also with `Jazz2_Android_DEBUG_ARM` build from GitHub Actions, please?

**Comment by Fancy2209** [comment]
> Can you test it also with `Jazz2_Android_DEBUG_ARM` build from GitHub Actions, please?

That works 
No crash

**Comment by deathkiller** [comment]
Good, and can you try also `Jazz2_Android_ARM` (the non-debug version?

**Comment by Fancy2209** [comment]
Only debug seems to build
/shrug

A sexta, 2/12/2022, 13:59, Dan R. ***@***.***> escreveu:
