### ISSUE TITLE
Wrong definition in AboutSection.cpp

### ISSUE THREAD

**Issue by musuruan** [deathkiller/jazz2-native#76]
The following line should define i7 and not i6:

https://github.com/deathkiller/jazz2-native/blob/a821b9cce81ad614dd71c7c488a35f3881468161/Sources/Jazz2/UI/Menu/AboutSection.cpp#L65C3-L65C9

**Comment by deathkiller** [comment]
Sorry, I was moving these texts multiple times and did this mistake. Should be fine now.
