### ISSUE TITLE
Switch Build 2.8.0 Crash on Startup

### ISSUE THREAD

**Issue by Paffo** [deathkiller/jazz2-native#79]
### Jazz² Resurrection version

2.7.0

### System information

Nintendo Switch (18.0,0) Atmosphere (1.7.0)

### Issue description

The latest build 2.8.0 crashes on startup.
The previous build 2.7.0 works flawlessly instead.

### Steps to reproduce

jazz2.nro inside sdmc:/switch/
all the levels into sdmc:/Games/Jazz2/Source

Starting (full RAM mode) the 2.8.0 NRO will cause the immediate crash, 2.7.0 works fine.

**Comment by deathkiller** [comment]
It's already fixed in the latest experimental build - https://nightly.link/deathkiller/jazz2-native/workflows/switch/master/Jazz2_Switch.zip
