### ISSUE TITLE
Your x64 Release builds are affected by a Visual studio bug that causes AVX instructions to be incorrectly used in SSE2/Not Set targets.

### ISSUE THREAD

**Issue by Squall-Leonhart** [deathkiller/jazz2-native#83]
### Jazz² Resurrection version

2.9.0

### System information

Windows 7, Xeon X5690 (Westmere, SSE4.2)

### Issue description

As such, only your x86 releases work on cpu's lacking AVX/2

### Steps to reproduce

See: https://developercommunity.visualstudio.com/t/An-AVX-instruction-is-generated-even-if-/10601714

clflushopt is the offending instruction this time round, rather than the one mentioned in that.

**Comment by Squall-Leonhart** [comment]
NVM, you've already addressed this for the next release.

**Comment by deathkiller** [comment]
Yes, it was my mistake, I thought the instruction is supported by all 64-bit CPUs, but it was added in Skylake. I probably have to release new version sooner because of this.
