### ISSUE TITLE
It's not entirely clear which files from the game are needed

### ISSUE THREAD

**Issue by grepwood** [deathkiller/jazz2-native#84]
A fresh GOG distribution of Jazz Jackrabbit 2 has 269 files. Which ones are actually needed by this engine?

**Comment by deathkiller** [comment]
`Anims.j2a` and `Data.j2d` are required, but then if you want to play any level, you need to include level files, tilesets, music.. videos are also separate if you want to watch them. So in the end you need most of them.

**Comment by grepwood** [comment]
Alright, I get the clue. I've copied 203 files - all which have an extension that starts with `j2`. Thanks! :)

**Comment by deathkiller** [comment]
I would say that's not enough, at least for music, but if you don't need it, why not.
