### ISSUE TITLE
Flathub version not updating

### ISSUE THREAD

**Issue by dragon99919** [deathkiller/jazz2-native#86]
### Jazz² Resurrection version

2.9.1

### System information

Linux Mint

### Issue description

It seems that while 2.9.1 was released two weeks ago, and Flathub manifest was updated to it, the site still states that the actual stable build is 2.9.0. I think the Flathub team should be contacted regarding this, maybe some sort of blockage appeared on their side?

### Steps to reproduce

Visit flathub page for the game and check last stable version.

**Comment by deathkiller** [comment]
It's successfully updated to v3.0.0. Probably some issues on their end.
