### ISSUE TITLE
Sticking jump and move commands

### ISSUE THREAD

**Issue by cosmincrihan** [deathkiller/jazz2-native#94]
### Jazz² Resurrection version

3.0.0: Highscores (commit ID 3b35747699dbf73f2b08bb296b3351629dae7fc6)

### System information

Debian 12 Bookworm, XFCE

### Issue description

Movement and jump keys are sometimes "sticking". I have the following keymap configuration:

![Screenshot_2024-12-27_11-37-29](https://github.com/user-attachments/assets/43dd50d9-0e51-444f-a4c1-23393225f32f)

So I am used to playing with left shift pressed to run, use CTRL to jump and space to fire.
The game sometimes sticks one of these keys even if I let go of them at all, for example I run, jump at the same time and while in the air I shoot, then land down and let go of the keyboard. Jazz will still jump continuously, just like the CTRL key hasn't been let go of. In other cases, one of the directional arrows gets sticky and Jazz will move on its own without me pressing anything.

Could you please help me with this issue? Thank you!

### Steps to reproduce

Assign:

- directional arrows for movement
- left CTRL for jumping
- SPACE for shooting
- left SHIFT for running

While keeping left SHIFT pressed for running, try moving your character, then jumping and shooting while in the air (so multiple of these buttons get pressed simultaneously). There is a high chance that one of them gets sticky and the character will either continue to jump on its own or move on its own without any key being pressed.

To release the "stickiness", you have to press the exact key that got stuck once again.

**Comment by deathkiller** [comment]
Is it GLFW build or SDL build? Can you try the other one? I'm not aware of this issue, it worked fine last time I tried it on Linux, and I didn't change anything. Can you try some other versions? Also you can try the web version to reduce the possible causes.

**Comment by cosmincrihan** [comment]
The GLFW build had this issue.
I also tried the SDL binary and I noticed something does change: keys do not stick anymore, however not all keystrokes are registered properly, for example when I am running in a direction and I quickly try to stop Jazz from moving and punch upwards with his special move, the "Up" command is not registered, it takes a few tries with "CTRL + Up arrow" to get the move to work.

Tested the web version too just now and it behaves just like the initial GLFW build, with keys getting stuck.

**Comment by deathkiller** [comment]
You mean Down arrow, not Up, right? Because Jump + Up does nothing.
I'm still not sure if it's really a bug in the game, I can't reproduce it even on Linux with Gnome. It looks like some issues with your system (or maybe GLFW library). Does it still happen even if you change the controls to different keys? You can also try to unmap the gamepad bindings with Delete key.

**Comment by cosmincrihan** [comment]
Yes, sorry. Down arrow it was.
I tried to unmap the gamepad specific keys but nothing changed.
However, I changed the controls to other keys, (Z, X, C) and the problem disappeared! Seems like the desktop environment might interfere with capturing the modifier keys, such as SHIFT, ALT and CTRL. Pesky XFCE...

Thank you very much for your help and suggestions!
I guess I'll just have to get used to working with letter bindings for Jazz's actions instead of the special modifier keys. No big deal, as long as it works fine.

**Comment by deathkiller** [comment]
You're welcome.
If other keys work fine, it's probably some bug/incompatibility in XFCE (along with GLFW/SDL library) with modifier keys and I can't help you with it unfortunately.
Feel free to reopen if you encounter any other problems.
